eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8003
spring:
  application:
    name: service-member
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web #网页展示
  sleuth:
    sampler:
      probability: 1.0

#读取配置文件的四个地方